[workspace]
members = [
  "crates/wist-contracts",
  "crates/wist-validate",
  "crates/wist-shared",
  "crates/warp-gateway",
  "crates/warp-agentd",
  "crates/wist-exec",
  "crates/wist-upgrader",
  "crates/wist-gateway",
  "crates/insight-control",
  "crates/wist-center",
  "crates/wist-observed",
  "crates/wist-security",
  "crates/wist-reporting",
  "crates/insight-simulator",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "Apache-2.0"
version = "0.1.1" #@gxl:set(version)
rust-version = "1.85"

[workspace.dependencies]
wist-contracts = { path = "crates/wist-contracts" }
wist-validate = { path = "crates/wist-validate" }
wist-shared = { path = "crates/wist-shared" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
time = { version = "0.3", features = ["formatting", "parsing"] }
toml = "0.8"
tokio = { version = "1.48", features = ["full"] }

[workspace.lints.clippy]
dbg_macro = "deny"
todo = "deny"
unwrap_used = "deny"
