# @moju generated
# @moju hash=d2b0d37b3a089d76

[package]
name = "warp-gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
moju-core = { path = "/Users/zuowenjian/devspace/rust/x-topology/moju-sys/moju-core" }
moju-derive = { path = "/Users/zuowenjian/devspace/rust/x-topology/moju-sys/moju-derive" }
axum = "0.7"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
toml = "0.8"
base64 = "0.22"
hyper = "1"
hyper-util = { version = "0.1", features = ["server-auto", "tokio", "service", "http1", "http2"] }
rustls = { version = "0.23", default-features = false, features = ["std", "ring"] }
rustls-pki-types = "1"
tokio-rustls = { version = "0.26", default-features = false, features = ["ring", "tls12", "logging"] }
warp-insight-contracts = { path = "../warp-insight-contracts" }
ring = "0.17"
serde_json = "1"

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
