[package]
name = "wist-shared"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
time.workspace = true
chrono = { version = "0.4", features = ["serde"] }

[lib]
path = "src/lib.rs"
