[package]
name = "warp-insight-reporting"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
moju-core = { path = "/Users/zuowenjian/devspace/rust/x-topology/moju-sys/moju-core" }
moju-derive = { path = "/Users/zuowenjian/devspace/rust/x-topology/moju-sys/moju-derive" }
serde = { version = "1", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
warp-insight-shared = { path = "../warp-insight-shared" }
