import type { TsModel } from "./types";

type WriteFile = (dir: string, filename: string, content: string) => void;
type EnsureDir = (...segments: string[]) => string;

export function generateIndexFiles(
  _model: TsModel,
  writeFile: WriteFile,
  _ensureDir: EnsureDir,
): void {
  // Top-level barrel exports are already generated by each generator.
  // This centralizes any additional index files needed.

  // src/index.ts — main barrel export
  writeFile(
    "src",
    "index.ts",
    `export * from "./components";
export * from "./hooks";
export * from "./api";
export * from "./store";
export * from "./types";
`,
  );
}
